services:

    _defaults:
        autowire:   true
        autoconfigure: true

    ################################################################################
    # AutoWire for Actions
    BadPixxel\SonataPageExtra\Actions\:
        resource:   '../../Actions'
        tags:       ["controller.service_arguments"]

    ################################################################################
    # AutoWire for Commands
    BadPixxel\SonataPageExtra\Command\:
        resource:   '../../Command'

    ################################################################################
    # AutoWire for Configurators
    BadPixxel\SonataPageExtra\Configuration\:
        resource:   '../../Configuration'

    ################################################################################
    # AutoWire for Sonata Page Services
    BadPixxel\SonataPageExtra\Page\:
        resource:   '../../Page'

    ################################################################################
    # AutoWire for Sonata Page Routers
    BadPixxel\SonataPageExtra\Route\:
        resource:   '../../Route'

    ################################################################################
    # AutoWire for Sonata Top Level Services
    BadPixxel\SonataPageExtra\Services\:
        resource:   '../../Services'

    ################################################################################
    # AutoWire for Sonata Sitemaps Iterators
    BadPixxel\SonataPageExtra\Sitemaps\:
        resource:   '../../Sitemaps'

    ################################################################################
    # AutoWire for Twig Extensions
    BadPixxel\SonataPageExtra\Twig\:
        resource:   '../../Twig'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        test.client:
            class:  BadPixxel\SonataPageExtra\Phpunit\HttpSiteBrowser
            public: true

